---
config:
  layout: dagre
---
flowchart TD
    A["Inicio"] --> B["Colocación de vincha EEG"]
    B --> C["Detección de señales cerebrales - ondas beta"]
    C --> D["Filtrado pasa-banda 13–30 Hz""]
    D --> D1["Acondicionamiento de la señal"]
    D1 --> D2["Amplificación final y limpieza de ruido"]
    D2 --> D3["Conversión ADC - ESP32-C3 (12 bits)"]
    D3 --> E["Cálculo RMS"]
    E --> F{"¿Amplitud beta supera el umbral?"}

    F -- Sí --> G["Activar retroalimentación: alerta en app"]
    F -- No --> H["Continuar monitoreo con normalidad"]

    G --> I["Mostrar estado y nivel en interfaz gráfica"]
    H --> I

    I --> J{"¿Finaliza sesión?"}
    J -- No --> C
    J -- Sí --> K["Fin"]

    style A fill:#e3fcef,stroke:#2ecc71,stroke-width:2px
    style K fill:#fcefee,stroke:#e74c3c,stroke-width:2px
